# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rz/Documents/octop-os

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rz/Documents/octop-os

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rz/Documents/octop-os/CMakeFiles /home/rz/Documents/octop-os//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rz/Documents/octop-os/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named octo

# Build rule for target.
octo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 octo
.PHONY : octo

# fast build rule for target.
octo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octo.dir/build.make CMakeFiles/octo.dir/build
.PHONY : octo/fast

src/installer/client/libinstall.o: src/installer/client/libinstall.c.o

.PHONY : src/installer/client/libinstall.o

# target to build an object file
src/installer/client/libinstall.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octo.dir/build.make CMakeFiles/octo.dir/src/installer/client/libinstall.c.o
.PHONY : src/installer/client/libinstall.c.o

src/installer/client/libinstall.i: src/installer/client/libinstall.c.i

.PHONY : src/installer/client/libinstall.i

# target to preprocess a source file
src/installer/client/libinstall.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octo.dir/build.make CMakeFiles/octo.dir/src/installer/client/libinstall.c.i
.PHONY : src/installer/client/libinstall.c.i

src/installer/client/libinstall.s: src/installer/client/libinstall.c.s

.PHONY : src/installer/client/libinstall.s

# target to generate assembly for a file
src/installer/client/libinstall.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octo.dir/build.make CMakeFiles/octo.dir/src/installer/client/libinstall.c.s
.PHONY : src/installer/client/libinstall.c.s

src/installer/client/unpack.o: src/installer/client/unpack.c.o

.PHONY : src/installer/client/unpack.o

# target to build an object file
src/installer/client/unpack.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octo.dir/build.make CMakeFiles/octo.dir/src/installer/client/unpack.c.o
.PHONY : src/installer/client/unpack.c.o

src/installer/client/unpack.i: src/installer/client/unpack.c.i

.PHONY : src/installer/client/unpack.i

# target to preprocess a source file
src/installer/client/unpack.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octo.dir/build.make CMakeFiles/octo.dir/src/installer/client/unpack.c.i
.PHONY : src/installer/client/unpack.c.i

src/installer/client/unpack.s: src/installer/client/unpack.c.s

.PHONY : src/installer/client/unpack.s

# target to generate assembly for a file
src/installer/client/unpack.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octo.dir/build.make CMakeFiles/octo.dir/src/installer/client/unpack.c.s
.PHONY : src/installer/client/unpack.c.s

src/installer/client/utils.o: src/installer/client/utils.c.o

.PHONY : src/installer/client/utils.o

# target to build an object file
src/installer/client/utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octo.dir/build.make CMakeFiles/octo.dir/src/installer/client/utils.c.o
.PHONY : src/installer/client/utils.c.o

src/installer/client/utils.i: src/installer/client/utils.c.i

.PHONY : src/installer/client/utils.i

# target to preprocess a source file
src/installer/client/utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octo.dir/build.make CMakeFiles/octo.dir/src/installer/client/utils.c.i
.PHONY : src/installer/client/utils.c.i

src/installer/client/utils.s: src/installer/client/utils.c.s

.PHONY : src/installer/client/utils.s

# target to generate assembly for a file
src/installer/client/utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octo.dir/build.make CMakeFiles/octo.dir/src/installer/client/utils.c.s
.PHONY : src/installer/client/utils.c.s

src/sdk/app.o: src/sdk/app.c.o

.PHONY : src/sdk/app.o

# target to build an object file
src/sdk/app.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octo.dir/build.make CMakeFiles/octo.dir/src/sdk/app.c.o
.PHONY : src/sdk/app.c.o

src/sdk/app.i: src/sdk/app.c.i

.PHONY : src/sdk/app.i

# target to preprocess a source file
src/sdk/app.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octo.dir/build.make CMakeFiles/octo.dir/src/sdk/app.c.i
.PHONY : src/sdk/app.c.i

src/sdk/app.s: src/sdk/app.c.s

.PHONY : src/sdk/app.s

# target to generate assembly for a file
src/sdk/app.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octo.dir/build.make CMakeFiles/octo.dir/src/sdk/app.c.s
.PHONY : src/sdk/app.c.s

src/sdk/robmov.o: src/sdk/robmov.c.o

.PHONY : src/sdk/robmov.o

# target to build an object file
src/sdk/robmov.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octo.dir/build.make CMakeFiles/octo.dir/src/sdk/robmov.c.o
.PHONY : src/sdk/robmov.c.o

src/sdk/robmov.i: src/sdk/robmov.c.i

.PHONY : src/sdk/robmov.i

# target to preprocess a source file
src/sdk/robmov.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octo.dir/build.make CMakeFiles/octo.dir/src/sdk/robmov.c.i
.PHONY : src/sdk/robmov.c.i

src/sdk/robmov.s: src/sdk/robmov.c.s

.PHONY : src/sdk/robmov.s

# target to generate assembly for a file
src/sdk/robmov.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octo.dir/build.make CMakeFiles/octo.dir/src/sdk/robmov.c.s
.PHONY : src/sdk/robmov.c.s

src/sdk/sampleapp.o: src/sdk/sampleapp.c.o

.PHONY : src/sdk/sampleapp.o

# target to build an object file
src/sdk/sampleapp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octo.dir/build.make CMakeFiles/octo.dir/src/sdk/sampleapp.c.o
.PHONY : src/sdk/sampleapp.c.o

src/sdk/sampleapp.i: src/sdk/sampleapp.c.i

.PHONY : src/sdk/sampleapp.i

# target to preprocess a source file
src/sdk/sampleapp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octo.dir/build.make CMakeFiles/octo.dir/src/sdk/sampleapp.c.i
.PHONY : src/sdk/sampleapp.c.i

src/sdk/sampleapp.s: src/sdk/sampleapp.c.s

.PHONY : src/sdk/sampleapp.s

# target to generate assembly for a file
src/sdk/sampleapp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octo.dir/build.make CMakeFiles/octo.dir/src/sdk/sampleapp.c.s
.PHONY : src/sdk/sampleapp.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... octo"
	@echo "... src/installer/client/libinstall.o"
	@echo "... src/installer/client/libinstall.i"
	@echo "... src/installer/client/libinstall.s"
	@echo "... src/installer/client/unpack.o"
	@echo "... src/installer/client/unpack.i"
	@echo "... src/installer/client/unpack.s"
	@echo "... src/installer/client/utils.o"
	@echo "... src/installer/client/utils.i"
	@echo "... src/installer/client/utils.s"
	@echo "... src/sdk/app.o"
	@echo "... src/sdk/app.i"
	@echo "... src/sdk/app.s"
	@echo "... src/sdk/robmov.o"
	@echo "... src/sdk/robmov.i"
	@echo "... src/sdk/robmov.s"
	@echo "... src/sdk/sampleapp.o"
	@echo "... src/sdk/sampleapp.i"
	@echo "... src/sdk/sampleapp.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

